# Generated by Django 3.0.4 on 2020-04-15 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='blogpost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Blogpost'),
            preserve_default=False,
        ),
    ]
